### ISSUE TITLE
If your thesis are available for download?

### ISSUE THREAD

**Issue by GUIMINLONG** [nkueng/SparseSuit#1]
Hi Nicola,
Very appreciate for your sharing of this project. I am new learner in this area, and interested in your work. Could you please tell me if your thesis is available for download? I just want to learn more about this project? Thx.

**Comment by nkueng** [comment]
Hi GUIMINLONG, the thesis was written in collaboration with a private company, so unfortunately, I currently cannot share the written report with you. This might change in the future. My code is largely based on the [Deep Inertial Poser](https://github.com/eth-ait/dip18), so you might wanna check out that.
